## NumPy(Numerical Python)
- Numpy is a open source Python Package
- Numpy arrays stores only homogeneous data
- Used for scientific calculations in python
- it is mainly working with arrays
- A Numpy array is multidimensional array
- It is used to create multidimensional arrays for fast operations
- If you want to install numpy(In other idle's)
    - pip install numpy

In [34]:
import numpy as np

In [8]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [9]:
li=[1,2,3,4,5]
print(li)
print(type(li))

[1, 2, 3, 4, 5]
<class 'list'>


In [10]:
a=np.array(li)    #array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
b=np.array([[4,5,6,7],[9,8,7,6]])
print(b)
type(b)
print(b.ndim)
print(b.shape)
print(d.itemsize)

[[4 5 6 7]
 [9 8 7 6]]
2
(2, 4)


NameError: name 'd' is not defined

In [ ]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(type(c))
print(c.ndim)
print(c.shape)

In [ ]:
print(c.dtype)
print(c.nbytes)
print(c.size)

In [ ]:
d=np.array([23,4.5,6.7,65])
print(d)
print(d.dtype)
print(d.nbytes)
print(d.itemsize)
print(len(d))

In [ ]:
e=np.append(d,[45,67])
print(e)

In [ ]:
h=np.array(e,ndmin=10)
print(h)

In [ ]:
np.__version__

In [ ]:
e.itemsize

In [ ]:
g=np.array(((2,3,4,5),(7,8,9,10)))
print(g)
print(g.dtype)
print(g.nbytes)
print(g.itemsize)
print(len(g))
print(type(g))

In [ ]:
a

In [ ]:
print(a[2])
print(a[-1])
print(a[4])
print(a[0])

In [ ]:
b

In [ ]:
print(b[1,1])
print(b[-1,-3])
print(b[-2,-3])
print(b[:,:2])

In [ ]:
print(b[-2,1])
print(b[-1,:-2])
print(b[:,2])

In [ ]:
c

In [ ]:
print(c[1,1,1])
print(c[1,0,1])
print(c[:,:,1])
print(c[:,1,:])

In [ ]:
#range
a=np.array(range(10))
print(a)
print(type(a))

In [ ]:
#arange
b=np.arange(10)
print(b)
print(type(b))

In [12]:
c=np.arange(2,11,2)
print(c)

[ 2  4  6  8 10]


In [13]:
#reshape
d=np.arange(10).reshape(5,2)
d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [14]:
e=np.array([3,4,5,6],ndmin=3)
e

array([[[3, 4, 5, 6]]])

In [15]:
import numpy
print(dir(numpy))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

In [16]:
a=np.arange(1,40,2).reshape(5,4)
a

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31],
       [33, 35, 37, 39]])

In [17]:
a=np.linspace(1,30,30)
c=a.reshape(5,3,2)
c

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]],

       [[13., 14.],
        [15., 16.],
        [17., 18.]],

       [[19., 20.],
        [21., 22.],
        [23., 24.]],

       [[25., 26.],
        [27., 28.],
        [29., 30.]]])

In [18]:
b=np.logspace(1,20,10)
b

array([1.00000000e+01, 1.29154967e+03, 1.66810054e+05, 2.15443469e+07,
       2.78255940e+09, 3.59381366e+11, 4.64158883e+13, 5.99484250e+15,
       7.74263683e+17, 1.00000000e+20])

In [19]:
#Zeros
c=np.zeros((5,5),dtype=int)
c

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
#ones
d=np.ones((3,3),dtype=str)
d

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [21]:
#full
x=np.full((4,3),'python')
x

array([['python', 'python', 'python'],
       ['python', 'python', 'python'],
       ['python', 'python', 'python'],
       ['python', 'python', 'python']], dtype='<U6')

In [22]:
np.diag(x)

array(['python', 'python', 'python'], dtype='<U6')

In [23]:
a=np.random.randint(1,30)
a

11

In [24]:
b=np.random.randint(1,30,12).reshape(3,4)
b

array([[ 2, 28, 25, 23],
       [18,  5, 22, 22],
       [17, 27, 23, 11]])

In [25]:
c=np.random.randn(2,4)
c

array([[ 0.87077904,  1.7450967 , -1.93540953,  0.73652595],
       [ 2.52783098, -0.77560711, -0.3800405 , -1.03729702]])

In [26]:
e=np.random.random((2,4))
e

array([[0.26499313, 0.49068094, 0.23779061, 0.47437358],
       [0.92495741, 0.49682242, 0.20885177, 0.25123726]])

In [27]:
d=np.random.randint(1,40,(4,3))
d

array([[25, 39, 19],
       [30, 36, 23],
       [ 8,  8, 30],
       [17,  9, 12]])

In [28]:
print(d>25)

[[False  True False]
 [ True  True False]
 [False False  True]
 [False False False]]


In [29]:
print(d[d>25])

[39 30 36 30]


In [30]:
d[d>25].sum()

135

In [31]:
d.sum()

256

In [32]:
d.max()

39

In [33]:
d.mean()

21.333333333333332

In [34]:
np.median(d)

21.0

In [35]:
d.min()

8

In [36]:
print(b)

[[ 2 28 25 23]
 [18  5 22 22]
 [17 27 23 11]]


In [37]:
a=np.random.randint(1,20,12).reshape(3,4)
print(a)

[[ 5 17  9 10]
 [14  8  5  5]
 [ 7 14 17 16]]


In [38]:
print(a+10)
print(a+b)
print(a-b)
print(a@b)

[[15 27 19 20]
 [24 18 15 15]
 [17 24 27 26]]
[[ 7 45 34 33]
 [32 13 27 27]
 [24 41 40 27]]
[[  3 -11 -16 -13]
 [ -4   3 -17 -17]
 [-10 -13  -6   5]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [39]:
print(a%b)

[[ 1 17  9 10]
 [14  3  5  5]
 [ 7 14 17  5]]


In [40]:
np.log2(2)

1.0

In [41]:
np.argmin(a)

0

In [42]:
np.argmax(a)

1

In [52]:
np.exp(1)

2.718281828459045

In [53]:
np.cos(30)

0.15425144988758405

In [56]:
print(b.dot(a))

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [54]:
np.sin(45)

0.8509035245341184

In [55]:
np.tan(90)

-1.995200412208242

In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

array(['123abc', 'Helloxyz'], dtype='<U14')

In [7]:
print(dir(np.char))

['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_binary_op_dispatcher', '_center_dispatcher', '_clean_args', '_code_dispatcher', '_count_dispatcher', '_endswith_dispatcher', '_expandtabs_dispatcher', '_get_num_chars', '_globalvar', '_join_dispatcher', '_just_dispatcher', '_mod_dispatcher', '_multiply_dispatcher', '_partition_dispatcher', '_replace_dispatcher', '_split_dispatcher', '_splitlines_dispatcher', '_startswith_dispatcher', '_strip_dispatcher', '_to_string_or_unicode_array', '_translate_dispatcher', '_unary_op_dispatcher', '_use_unicode', '_vec_string', '_zfill_dispatcher', 'add', 'array', 'array_function_dispatch', 'asarray', 'asbytes', 'bool_', 'capitalize', 'center', 'character', 'chararray', 'compare_chararrays', 'count', 'decode', 'encode', 'endswith', 'equal', 'expandtabs', 'find', 'functools', 'greater', 'greater_equal', 'index', 'int_', 'integer', 'isalnum', 'isalpha', 'isdecimal', 'isdigit', 'islowe

In [37]:
np.char.add([123, 'Hello'],['abc','xyz'])# to concatinate

array(['123abc', 'Helloxyz'], dtype='<U14')

In [39]:
np.char.array(['apssdc JNTU', 'Viziyanagaram'])

chararray(['apssdc JNTU', 'Viziyanagaram'], dtype='<U13')

In [11]:
help(np.char.endswith)

Help on function endswith:

endswith(a, suffix, start=0, end=None)
    Returns a boolean array which is `True` where the string element
    in `a` ends with `suffix`, otherwise `False`.
    
    Calls `str.endswith` element-wise.
    
    Parameters
    ----------
    a : array_like of str or unicode
    
    suffix : str
    
    start, end : int, optional
        With optional `start`, test beginning at that position. With
        optional `end`, stop comparing at that position.
    
    Returns
    -------
    out : ndarray
        Outputs an array of bools.
    
    See also
    --------
    str.endswith
    
    Examples
    --------
    >>> s = np.array(['foo', 'bar'])
    >>> s[0] = 'foo'
    >>> s[1] = 'bar'
    >>> s
    array(['foo', 'bar'], dtype='<U3')
    >>> np.char.endswith(s, 'ar')
    array([False,  True])
    >>> np.char.endswith(s, 'a', start=1, end=2)
    array([False,  True])



In [40]:
s1 = ['python','DataAnalysis']
np.char.endswith(s1,'is')

array([False,  True])

In [43]:
s2 = ['sirEEshA','GirEEshA']
np.char.swapcase(s2)

array(['SIReeSHa', 'gIReeSHa'], dtype='<U8')

In [47]:
np.char.title(['python subject','data analysis'])

array(['Python Subject', 'Data Analysis'], dtype='<U14')

In [46]:
np.char.capitalize(['python subject','data analysis'])

array(['Python subject', 'Data analysis'], dtype='<U14')

In [50]:
np.sort(s2)# based on ASCII values

array(['GirEEshA', 'sirEEshA'], dtype='<U8')

In [24]:
a = np.array([[7,7,0,7],[2,0,7,0],[7,7,1,7]])
a

array([[7, 7, 0, 7],
       [2, 0, 7, 0],
       [7, 7, 1, 7]])

In [51]:
a.shape

(3, 4)

In [41]:
a[1]

array([2, 0, 7, 0])

In [42]:
a[1,0:2]

array([2, 0])

In [25]:
np.mean(a,0)

array([5.33333333, 4.66666667, 2.66666667, 4.66666667])

In [26]:
np.sort(a,0)

array([[2, 0, 0, 0],
       [7, 7, 1, 7],
       [7, 7, 7, 7]])

In [28]:
help(a.nonzero)

Help on built-in function nonzero:

nonzero(...) method of numpy.ndarray instance
    a.nonzero()
    
    Return the indices of the elements that are non-zero.
    
    Refer to `numpy.nonzero` for full documentation.
    
    See Also
    --------
    numpy.nonzero : equivalent function



In [29]:
a2 = np.array([[0,22,55,0],[1,12,0,3]])
a2

array([[ 0, 22, 55,  0],
       [ 1, 12,  0,  3]])

In [30]:
a2.nonzero()

(array([0, 0, 1, 1, 1], dtype=int64), array([1, 2, 0, 1, 3], dtype=int64))

In [31]:
a2>10

array([[False,  True,  True, False],
       [False,  True, False, False]])

In [32]:
np.where(a2>10)

(array([0, 0, 1], dtype=int64), array([1, 2, 1], dtype=int64))

In [49]:
a2

array([[ 0, 22, 55,  0],
       [ 1, 12,  0,  3]])

In [48]:
np.hstack(a2)

array([ 0, 22, 55,  0,  1, 12,  0,  3])